// {{PKG_NAME}} — HOST half of a preset pack (generated by create-dsh-plugin).
//
// What a preset pack is: a plugin that SHIPS agent presets (persona +
// composition, same format as the official "Standard / 极简" presets) and lets
// the user apply them from a settings panel. Applying = copying presets/<id>/
// into the DSH user preset root `<dshHome>/.agent-presets/<id>/`; the official
// agent-presets plugin discovers that root LIVE (re-reads on every call), so an
// applied preset appears in Settings > Agent presets immediately — no restart.
//
// This skeleton is distilled from the preset-center package: list/apply/remove
// routes + the presets/ directory layout. Replace the example preset with your
// own personas.
//
import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { homedir } from 'node:os'
import type { Context } from '@deepseek-ai/cordis'

export const name = '{{PLUGIN_ID}}'
export const inject = ['webServer']

const HERE = dirname(fileURLToPath(import.meta.url))
const PRESETS_DIR = join(HERE, '..', 'presets')

function dshHome() {
  return process.env.DSH_HOME || join(homedir(), '.dsh')
}
function userRoot() {
  return join(dshHome(), '.agent-presets')
}

/** Read a preset's display metadata from its preset.yml (name/description/order). */
function readPreset(id: string) {
  const meta = readFileSync(join(PRESETS_DIR, id, 'preset.yml'), 'utf8')
  const name = /^name:\s*(.+)$/m.exec(meta)?.[1]?.trim() || id
  const description = /^description:\s*(.+)$/m.exec(meta)?.[1]?.trim() || ''
  const order = Number(/^order:\s*(\d+)$/m.exec(meta)?.[1] ?? 0)
  return {
    id,
    name,
    description,
    order,
    applied: existsSync(join(userRoot(), id, 'agent.cordis.yml')),
  }
}

function listPresets() {
  return readdirSync(PRESETS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .map(readPreset)
}

function applyPreset(id: string) {
  const src = join(PRESETS_DIR, id)
  if (!existsSync(join(src, 'agent.cordis.yml'))) return { ok: false, error: 'unknown preset: ' + id }
  const dst = join(userRoot(), id)
  mkdirSync(dst, { recursive: true })
  for (const f of ['agent.cordis.yml', 'preset.yml']) {
    writeFileSync(join(dst, f), readFileSync(join(src, f)))
  }
  return { ok: true, id, files: [join(dst, 'agent.cordis.yml'), join(dst, 'preset.yml')] }
}

function removePreset(id: string) {
  const dst = join(userRoot(), id)
  if (existsSync(dst)) rmSync(dst, { recursive: true, force: true })
  return { ok: true, id }
}

type WebServer = {
  register: (spec: { kind: 'exact' | 'prefix'; path: string; handler: (req: any, res: any) => void }) => () => void
}

export function apply(ctx: Context) {
  const ws = (ctx as unknown as { webServer: WebServer }).webServer

  ctx.effect(() => {
    const text = (code: number, body: Buffer, mime: string) => (req: any, res: any) => {
      res.writeHead(code, { 'content-type': mime, 'content-length': body.length })
      res.end(body)
    }
    const json = (body: unknown) => {
      const buf = Buffer.from(JSON.stringify(body), 'utf8')
      return text(200, buf, 'application/json; charset=utf-8')
    }

    const d1 = ws.register({ kind: 'exact', path: '/{{PLUGIN_ID}}/list', handler: (_req, res) => json(listPresets())(_req, res) })
    const d2 = ws.register({ kind: 'exact', path: '/{{PLUGIN_ID}}/apply', handler: (req, res) => {
      let raw = ''
      req.on('data', (c: Buffer) => { raw += c })
      req.on('end', () => {
        let id = ''
        try { id = String(JSON.parse(raw || '{}').id || '') } catch { /* ignore */ }
        json(id ? applyPreset(id) : { ok: false, error: 'missing id' })(req, res)
      })
    } })
    const d3 = ws.register({ kind: 'exact', path: '/{{PLUGIN_ID}}/remove', handler: (req, res) => {
      let raw = ''
      req.on('data', (c: Buffer) => { raw += c })
      req.on('end', () => {
        let id = ''
        try { id = String(JSON.parse(raw || '{}').id || '') } catch { /* ignore */ }
        json(id ? removePreset(id) : { ok: false, error: 'missing id' })(req, res)
      })
    } })
    return () => { d1(); d2(); d3() }
  }, '{{PLUGIN_ID}}: routes')
}
