// {{PKG_NAME}} — HOST half of a dual-half panel plugin (generated by create-dsh-plugin).
//
// Dual-half architecture in one paragraph:
//   - HOST half (this file, compiled to dist/index.js) runs in the DSH Node
//     process. It can do anything a plugin can: register tools, services, and
//     HTTP routes via `ctx.webServer`.
//   - BROWSER half (lib/client.js, served by the module loader) runs in the
//     DSH Web UI. It registers into official UI seams (here: `settings.section`,
//     the same slot General / Models / Plugins use) and talks to the host half
//     over fetch() to the routes registered below.
//
// This minimal skeleton is distilled from the skin-center / preset-center
// packages — it keeps ONLY the registration mechanics, no business code.
//
import type { Context } from '@deepseek-ai/cordis'

// Plugin display name, shown in loader diagnostics.
export const name = '{{PLUGIN_ID}}'

// Wait until the host's HTTP server (`ctx.webServer`) is ready before running.
export const inject = ['webServer']

// Minimal typed view of the webServer seam. The full API lives in
// @deepseek-ai/dsh-web-server; a plugin only needs `register` (which returns a
// disposer — call it to unregister, e.g. inside ctx.effect cleanup).
interface RouteSpec {
  kind: 'exact' | 'prefix'
  path: string
  handler: (req: any, res: any) => void
}
type WebServer = { register: (spec: RouteSpec) => () => void }

export function apply(ctx: Context) {
  const ws = (ctx as unknown as { webServer: WebServer }).webServer

  // Node http-style res: writeHead + end. Keep responses JSON for the client.
  const json = (body: unknown) => (_req: any, res: any) => {
    const buf = Buffer.from(JSON.stringify(body), 'utf8')
    res.writeHead(200, {
      'content-type': 'application/json; charset=utf-8',
      'content-length': buf.length,
    })
    res.end(buf)
  }

  // Register the route inside ctx.effect so it is cleaned up on unload.
  ctx.effect(() => {
    const dispose = ws.register({
      kind: 'exact',
      path: '/{{PLUGIN_ID}}/ping',
      handler: json({ ok: true, plugin: '{{PLUGIN_ID}}', time: new Date().toISOString() }),
    })
    console.log(`[{{PLUGIN_ID}}] route /{{PLUGIN_ID}}/ping registered`)
    return dispose
  }, '{{PLUGIN_ID}}: routes')
}
