// {{PKG_NAME}} — a lifecycle/event plugin (generated by create-dsh-plugin).
//
// Unlike the `tool` template, this one has ZERO runtime dependencies: it only
// uses the `ctx` the host hands it, and every type import below is erased at
// compile time (`import type`), so nothing is imported at runtime.
//
import type { Context } from '@deepseek-ai/cordis'
import type { Session, SessionEvent } from '@deepseek-ai/dsh-session'
import type { PreToolDecision, ToolExecution } from '@deepseek-ai/dsh-tools'

// Plugin display name, shown in loader diagnostics.
export const name = '{{PLUGIN_ID}}'

export function apply(ctx: Context) {
  let sessionEvents = 0
  let toolChanges = 0
  let toolPreExecutes = 0

  // ① Durable session firehose (emit): fires whenever a session's log grows —
  //    turn/step boundaries, user/assistant messages, tool results, …
  ctx.on('session/event', (session: Session, event: SessionEvent) => {
    sessionEvents += 1
    if (sessionEvents <= 5 || sessionEvents % 25 === 0) {
      console.log(
        `[{{PLUGIN_ID}}] session/event #${sessionEvents} type=${event.type} session=${String(session.id)}`,
      )
    }
  })

  // ② Live registry change (emit): fires the moment any tool is registered or
  //    unregistered — including by sibling plugins in the same composition.
  ctx.on('tools/change', () => {
    toolChanges += 1
    console.log(`[{{PLUGIN_ID}}] tools/change #${toolChanges}`)
  })

  // ③ Tool execution pipeline (waterfall): log, then delegate with next().
  //    NOT calling next() would short-circuit and block the tool call.
  ctx.on('tools/pre-execute', (exec: ToolExecution, next: () => Promise<PreToolDecision>) => {
    toolPreExecutes += 1
    console.log(`[{{PLUGIN_ID}}] tools/pre-execute #${toolPreExecutes} tool=${exec.name}`)
    return next()
  })

  // ④ ctx.on() is already an EFFECT (auto-disposed on unload). For a resource
  //    Cordis does NOT manage (a timer/connection/watcher), wrap it in
  //    ctx.effect() and return a disposer — the reversible-cleanup proof:
  //    unload this plugin and watch the DISPOSED line print.
  ctx.effect(() => {
    const timer = setInterval(() => {
      console.log(
        `[{{PLUGIN_ID}}] heartbeat sessionEvents=${sessionEvents} toolPreExecutes=${toolPreExecutes} toolChanges=${toolChanges}`,
      )
    }, 30_000)
    return () => {
      clearInterval(timer)
      console.log(`[{{PLUGIN_ID}}] DISPOSED — listeners removed, timer cleared`)
    }
  })

  console.log(`[{{PLUGIN_ID}}] listeners registered: session/event + tools/change + tools/pre-execute`)
}
