// {{PKG_NAME}} — a tool with a Web UI card (generated by create-dsh-plugin).
//
// EXPERIMENTAL: this template shows the TOOL-SIDE Web UI extension — the
// `presentCall`/`presentResult` "card" render intent (a diff card here). A full
// ConversationNodeDefinition (a brand-new row type in the Chat view) lives in
// `@deepseek-ai/dsh-client-*` and is a separate, more involved extension point
// (see docs/cookbook/adding-a-conversation-node.md in the harness repo).
//
// ── Pitfalls this file guards against ─────────────────────────────────────
// 1. presentCall/presentResult MUST be pure (they run on live streaming AND on
//    session-log replay): no I/O, no clock/random, no session state.
// 2. `presentationMeta` is the REPLAYABLE bridge: it derives card data from the
//    canonical value (and args) and is persisted on `tool/result`, so the card
//    can be rebuilt on replay. Do not read files/clock inside the presenters.
// 3. Object output schema MUST declare `additionalProperties`; `required: true`
//    keeps `value` non-optional in render()/presentationMeta().
//
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'

// Plugin display name, shown in loader diagnostics.
export const name = '{{PLUGIN_ID}}'

// Wait until the host's tool registry (`ctx.tools`) is ready before running.
export const inject = ['tools']

export function apply(ctx: Context) {
  ctx.tools.register(defineTool({
    name: '{{TOOL_NAME}}',
    description: 'Write a short note to a file and show an inline diff card (Web UI extension demo).',

    parameters: {
      path: { type: 'string', required: true, description: 'Absolute path to write.' },
      content: { type: 'string', required: true, description: 'Note content.' },
    },

    output: {
      schema: {
        type: 'object',
        properties: {
          path: { type: 'string', required: true, description: 'Absolute path written.' },
          bytes: { type: 'integer', required: true, description: 'Bytes written.' },
        },
        additionalProperties: false,
      },
      render: (_args, value) => [{ type: 'text', text: `Wrote ${value.bytes} bytes to ${value.path}` }],
      // Replayable card data: combine args + canonical value so the card can be
      // rebuilt from the persisted tool/result event on replay.
      presentationMeta: (args, value) => ({ path: value.path, content: args.content }),
    },

    // Pending card (a diff card — this call creates a file, so oldText is null).
    presentCall: (args) => ({
      card: 'diff',
      title: `Write ${args.path}`,
      diffs: [{ path: args.path, oldText: null, newText: args.content }],
      locations: [{ path: args.path }],
    }),

    // Completed card: rebuild the applied hunk from the persisted meta.
    presentResult: (_args, result) => {
      const meta = result.meta as { path?: string; content?: string } | undefined
      const path = meta?.path ?? ''
      return {
        card: 'diff',
        title: `Wrote ${path}`,
        diffs: [{ path, oldText: null, newText: meta?.content ?? '' }],
      }
    },

    async execute(args) {
      const abs = resolve(args.path)
      await writeFile(abs, args.content, 'utf8')
      return { path: abs, bytes: Buffer.byteLength(args.content, 'utf8') }
    },
  }))

  console.log(
    `[{{PLUGIN_ID}}] registered "{{TOOL_NAME}}" (webui diff card) — listed=${ctx.tools.get('{{TOOL_NAME}}') !== undefined}`,
  )
}
