// {{PKG_NAME}} — a `defineTool` tool plugin (generated by create-dsh-plugin).
//
// ── Pitfalls this file already guards against ─────────────────────────────
// 1. `@deepseek-ai/dsh-tools` is pinned to the `next`-tag version in
//    package.json — npm's `latest` tag is a STALE 0.0.1-rc.1. Never run a bare
//    `npm i @deepseek-ai/dsh-tools` over it.
// 2. Registration is an EFFECT: `ctx.tools.register()` returns a disposer and
//    auto-attaches it to this plugin's fiber, so unloading unregisters the tool.
// 3. Load order = service dependencies (`inject`), never file order.
// 4. Pure ESM (`"type": "module"`); `@deepseek-ai/cordis` is types-only here
//    (`import type` is erased at compile — the host hands you `ctx` at runtime).
// 5. An object output schema MUST declare `additionalProperties` explicitly.
//    Marking each property `required: true` keeps `value` non-optional so
//    `render`/`presentationMeta` type-check cleanly.
//
import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'

// Plugin display name, shown in loader diagnostics.
export const name = '{{PLUGIN_ID}}'

// Wait until the host's tool registry (`ctx.tools`) is ready before running.
export const inject = ['tools']

export function apply(ctx: Context) {
  ctx.tools.register(defineTool({
    // The name the model uses to call this tool.
    name: '{{TOOL_NAME}}',
    // What the model sees — keep it task-relevant.
    description: 'Return the current time and process environment info (example tool).',

    // Parameter schema: the model\'s JSON arguments are validated against this
    // BEFORE execute() runs, and `args` is typed from it. A field with
    // `required: true` is mandatory; a bare field is optional.
    parameters: {
      tz: {
        type: 'string',
        description: "IANA timezone name, e.g. 'Asia/Shanghai'. Defaults to the system local timezone.",
      },
    },

    output: {
      // Canonical JSON return value. Objects MUST set `additionalProperties`;
      // `required: true` marks every returned field (execute() always returns
      // them), which also makes `value` non-optional in render().
      schema: {
        type: 'object',
        properties: {
          iso: { type: 'string', required: true, description: 'ISO-8601 timestamp (UTC).' },
          unixMs: { type: 'integer', required: true, description: 'Unix epoch milliseconds.' },
          tz: { type: 'string', required: true, description: 'Timezone actually used.' },
          nodeVersion: { type: 'string', required: true, description: 'process.version' },
          platform: { type: 'string', required: true, description: 'process.platform' },
        },
        additionalProperties: false,
      },
      // render() projects the canonical value into model-facing content blocks.
      render: (_args, value) => [{ type: 'text', text: JSON.stringify(value, null, 2) }],
    },

    // execute() returns ONLY the canonical value declared by output.schema.
    // args is typed from the parameter schema: { tz?: string }.
    async execute(args) {
      const tz = args.tz ?? Intl.DateTimeFormat().resolvedOptions().timeZone
      const now = new Date()
      return {
        iso: now.toISOString(),
        unixMs: now.getTime(),
        tz,
        nodeVersion: process.version,
        platform: process.platform,
      }
    },
  }))

  // Self-check (spike-proven): confirm the tool actually landed in the registry.
  console.log(
    `[{{PLUGIN_ID}}] registered "{{TOOL_NAME}}" — listed=${ctx.tools.get('{{TOOL_NAME}}') !== undefined}`,
  )
}
