#!/usr/bin/env node
// DSH All-in-One aggregate (zero-dep) — generate/validate packages/all from aggregate.yml + member packages.
// Rerun after any member bump: node scripts/aggregate.mjs   |   --check to validate only.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const log = s => console.log('[aggregate]', s)

// ---- 针对性解析 aggregate.yml（我固定的格式，零依赖，可靠）----
const raw = readFileSync(join(ROOT, 'scripts', 'aggregate.yml'), 'utf8')
const metaName = (raw.match(/name:\s*'?([^'\n]+)/) || [])[1]?.trim().replace(/'$/,'')
const metaVer  = (raw.match(/version:\s*'?([^'\n]+)/) || [])[1]?.trim().replace(/'$/,'')
const outDirRaw = (raw.match(/dir:\s*([^\n]+)/) || [])[1]?.trim()
const patchRaw  = (raw.match(/patch:\s*([^\n]+)/) || [])[1]?.trim()
const members = [...raw.matchAll(/^\s*-\s*(.+?)\s*\|\s*(.+?)\s*$/gm)]
  .map(m => ({ path: m[1].trim().replace(/^'|'$/g,''), dep: m[2].trim().replace(/^'|'$/g,'') }))
const outDir = join(ROOT, outDirRaw || 'packages/all')
const patchFile = join(outDir, patchRaw || 'cordis.patch.yml')
const check = process.argv.includes('--check')

// ---- ^a.b.c satisfies version? (0.x locks minor) ----
function sat(range, v) {
  const rm = range.match(/^\^(\d+)\.(\d+)\.(\d+)$/), vm = v.match(/^(\d+)\.(\d+)\.(\d+)/)
  if (!rm || !vm) return null
  const [, ma, mi, pa] = rm.map(Number), [, va, vi, pi] = vm.map(Number)
  if (ma === 0) return va === 0 && vi === mi && pi >= pa
  return va === ma && vi >= mi
}
function member(dir) {
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  let id = null, name = null
  try { for (const l of readFileSync(join(dir, 'cordis.patch.yml'), 'utf8').split('\n')) {
    const i = l.match(/^\s*-\s*id:\s*(\S+)/), n = l.match(/^\s*name:\s*(\S+)/)
    if (i) id = i[1]; if (n) name = n[1] } } catch {}
  return { id: id || pkg.name.replace(/^@[^/]+\//, ''), name: name || pkg.name, version: pkg.version, pkgName: pkg.name }
}

log(`meta ${metaName}@${metaVer} · ${members.length} members · ${check ? 'CHECK' : 'generate'}`)
let bad = 0
const rows = members.map(m => {
  const mem = member(join(ROOT, m.path))
  const ok = sat(m.dep, mem.version)
  log(`  ${mem.pkgName}@${mem.version} dep ${m.dep} id=${mem.id} sat=${ok === null ? '?(manual)' : ok}`)
  if (ok === false) { bad++; log(`    ✗ bump dep in aggregate.yml`) }
  return { ...mem, dep: m.dep }
})
if (bad) { log(`✗ ${bad} member(s) out of range — abort`); process.exit(1) }
if (check) { log('✓ check ok'); process.exit(0) }

const head = `# DSH All-in-One bundle patch — AUTO-GENERATED by scripts/aggregate.mjs, do not edit.\n# Rerun after member bump: node scripts/aggregate.mjs. Source: scripts/aggregate.yml.\n`
writeFileSync(patchFile, head + '\n' + rows.map(r => `- insert:\n    - id: ${r.id}\n      name: '${r.pkgName}'`).join('\n') + '\n', 'utf8')
log(`✓ wrote ${patchFile}`)
const pj = JSON.parse(readFileSync(join(outDir, 'package.json'), 'utf8'))
for (const r of rows) pj.dependencies[r.pkgName] = r.dep
writeFileSync(join(outDir, 'package.json'), JSON.stringify(pj, null, 2) + '\n', 'utf8')
log('✓ synced dependencies -> packages/all/package.json')
